CREATE TABLE LIBRARY(
  LIB_ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DOWNLOAD_COUNT INT NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  URL VARCHAR(255)
);

CREATE INDEX IDX_LIB_NAME_ ON LIBRARY(NAME);

INSERT INTO LIBRARY (NAME, DOWNLOAD_COUNT, AUTHOR) VALUES ('org.junit', 30, 'stephen mulrennan');
